### ISSUE TITLE
get_stats() funtion is not defined

### ISSUE THREAD

**Issue by DongchanSeo** [liamhebert/FedFormer#2]
There's no definition of "get_stats" in TorchBatchRLAlgorithm(sac_algorithm.py).
so it makes an error like "AttributeError: 'TorchBatchRLAlgorithm' object has no attribute 'get_stats'"
Can you please check this issue?

**Comment by liamhebert** [comment]
Thank you for pointing this out. I recently made some edits to some files that were made recently. I must have missed uploading the edits to that file. Should be fixed now!
