### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './networks/qf1/encoder-0.pt'

### ISSUE THREAD

**Issue by jinzehe** [liamhebert/FedFormer#4]
Dear liamhebert,

Sincerely thank you for providing such a valuable code, but there seems to be some bugs when I trying to run this code.

When I run the main.py, something wrong happened, in ‘’fed_algorithm.py", line 92

Traceback (most recent call last):
  File "E:\hjz\FedFormer-main\FedFormer-main\main.py", line 217, in <module>
    main()
  File "D:\anaconda\envs\formernew\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda\envs\formernew\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\anaconda\envs\formernew\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\envs\formernew\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\hjz\FedFormer-main\FedFormer-main\main.py", line 214, in main
    experiment(variant)
  File "E:\hjz\FedFormer-main\FedFormer-main\main.py", line 166, in experiment
    algorithm.train()
  File "E:\hjz\FedFormer-main\FedFormer-main\fed_algorithm.py", line 92, in train
    torch.save(qf1[i], f'./networks/qf1/encoder-{i}.pt')
  File "D:\anaconda\envs\formernew\lib\site-packages\torch\serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "D:\anaconda\envs\formernew\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda\envs\formernew\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './networks/qf1/encoder-0.pt'

Thanks

**Comment by liamhebert** [comment]
Hi Jinzehe, 

Thanks for this! The fix for this is simple: the code expects that there exists the following folders:
- `networks/qf1`
- `networks/qf2`
- `networks/target_qf1`
- `networks/target_qf2`

I'll push a fix now to check for the existence of these folders and create them otherwise. To adapt your existing copy, just create those folders in your run directory. 

Sorry about that!
Liam

**Comment by jinzehe** [comment]
Thanks much for your reply，
Best wishes！😊😊






---Original---
From: "Liam ***@***.***&gt;
Date: Fri, Nov 8, 2024 00:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [liamhebert/FedFormer] FileNotFoundError: [Errno 2] No such fileor directory: './networks/qf1/encoder-0.pt' (Issue #4)




 
Hi Jinzehe,
 
Thanks for this! The fix for this is simple: the code expects that there exists the following folders:
  
networks/qf1
 
networks/qf2
 
networks/target_qf1
 
networks/target_qf2
  
I'll push a fix now to check for the existence of these folders and create them otherwise. To adapt your existing copy, just create those folders in your run directory.
 
Sorry about that!
 Liam

**Comment by jinzehe** [comment]
Dear liamhebert，
I feel sorry to trouble you again. 
When i look through the results in the tensorboard，I couldn’t found the image of fedformer(5) . But I could found reward curves  for each agent, could you please tell me how to find the final fusing results' photos? 

Thanks,
Best wishes to you!

**Comment by liamhebert** [comment]
Hi Jinzehe, 

No worries at all! I'm glad you are asking these questions :) The graphs we have represent the average performance of all the agents. The shaded area is the standard error between the seeds. You should be able to reproduce the charts by taking the average of the 5 agents. 

As for FedAvg: you would want to toggle this parameter to `False`

https://github.com/liamhebert/FedFormer/blob/8d7dc789fb22dee689c3ae71909ef13dbfa9fd35/main.py#L173

I'll update the comment to make it more obvious how to swap. Note that our FedAvg implementation is weighted by reward, as we found that to be more performant. If you'd like to return to the normal, unweighted FedAvg, you can uncomment these lines: 
https://github.com/liamhebert/FedFormer/blob/8d7dc789fb22dee689c3ae71909ef13dbfa9fd35/fed_algorithm.py#L109-L116

and comment the rest of the function (Or by replacing weights[it] to just `1 / len(networks)`).  Sorry that swap is a little janky.

Thanks!

**Comment by jinzehe** [comment]
Dear liamhebert，
Thank you very much for your patient explanations. And Your coding style is strict and neat, I have learned a lot from it. 😊
Thanks！ :)
Best wishes！
